services:
  - type: web
    name: healthcare-rag-backend
    env: python
    repo: https://github.com/samridh-111/AICA-healthcare-rag-assistant
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        value: "${SUPABASE_URL}"
      - key: SUPABASE_KEY
        value: "${SUPABASE_KEY}"
      - key: GROQ_API_KEY
        value: "${GROQ_API_KEY}"
      - key: DATABASE_URL
        value: "${DATABASE_URL}"
